version: "3.8"

services:
  backend:
    container_name: review-feedback-api
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    environment:
      - ANALYZER_MODE=mock
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge